core/templatetags/urls.py
from urllib.parse import urlparse, urlunparse
from django.http import QueryDict
from django import template

register = template.Library()

@register.simple_tag
def replace_query_param(url, param, value):
    (scheme, netloc, path, params, query, fragment) = urlparse(url)
    query_dict = QueryDict(query).copy()
    query_dict[param] = value
    query = query_dict.urlencode()
    return urlunparse((scheme, netloc, path, params, query, fragment))

triangle4kids/urls.py
from django.contrib import admin
from django.urls import path
# from core.views import EventListView
# from core.views import search
from . import settings
from core import views
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from django.views.generic import TemplateView

from core.views import BusinessResultsListView, EventResultsListView

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls import url, include
from django.contrib.auth.models import User

from rest_framework import routers
from api import views as api_views

from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register('businesses', api_views.BusinessViewset,
                api_views.BusinessLatLongViewset)
router.register('businesseslocation', api_views.BusinessLatLongViewset)
router.register('event', api_views.EventViewset, api_views.EventLatLongViewset)
router.register('eventlocation', api_views.EventLatLongViewset)

urlpatterns = [
    path(
        'accounts/password/reset/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_form.html'),
        name="password_reset"),
    path(
        'accounts/password/reset/done/',
        PasswordResetView.as_view(
            template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    path(
        'accounts/password/reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'),
        name="password_reset_confirm"),
    path(
        'accounts/password/done/',
        PasswordResetCompleteView.as_view(
            template_name='registration/password_reset_complete.html'),
        name="password_reset_complete"),
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path(
        'events-dropdown-select/', views.event_list_preset,
        name='event_list_preset'),
    path('events/', views.event_list_text, name='event_list_text'),
    path('events/submit/', views.submit_event_form, name='submit_event_form'),
    path('general/submit/', views.general_submit_form, name='general_submit_form'),
    path('events/<slug>/', views.event_detail, name='event_detail'),
   
    path('business/', BusinessResultsListView.as_view(), name='business_list'),
    path('event/', EventResultsListView.as_view(), name='event_list'),
    path('business/<slug>/', views.business_detail, name='business_detail'),
    path('businessnew/<slug>/', views.newbusiness_detail, name='newbusiness_detail'),
    path('directory/', views.business_directory, name='business_directory'),
    path('events_directory/', views.event_directory, name='event_directory'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('my-profile/', views.get_user_profile, name="get_user_profile"),
    path(
        'review/<id>/delete',
        views.user_delete_review,
        name="user_delete_review"),
    url(r'(?P<id>\d+)/favorite_event/$',
        views.favorite_event,
        name='favorite_event'),
    path(
        'event/<int:pk>/favorite_event/',
        views.favorite_event,
        name='favorite_event'),
    path('mapboxTest', views.mapboxTest, name='mapboxTest'),
    path('mapBoxPlotTest', views.mapBoxPlotTest, name='mapBoxPlotTest'),
    path('api/', include('rest_framework.urls')),
    path('api/', include((router.urls, 'core'), namespace="api")),
    url(r'^api/(?P<pk>[0-9]+)/$', api_views.BusinessDetailViewset),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField
from django.core.validators import MinValueValidator, MaxValueValidator
from phone_field import PhoneField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Business(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=255, blank=True)
    zipcode = models.CharField(max_length=16, blank=True)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    average_rating = models.FloatField(default="0")
    link = models.URLField(null=True, blank=True)
    categories = models.CharField(max_length=1024, blank=True)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField(upload_to='test_image', blank=True)

    class Meta:
        verbose_name_plural = "Businesses"

    def __str__(self):
        return self.name


class BusinessLatLong(models.Model):
    business = models.OneToOneField(
        Business, on_delete=models.CASCADE, related_name='location')
    location_name = models.CharField(max_length=512, blank=True)
    relevance = models.FloatField(default=0)
    latitude = models.FloatField(blank=True)
    longitude = models.FloatField(blank=True)


EVENT_TYPE = (
    ('day_camps', 'Day Camps'),
    ('residential_camps', 'Residential Camps'),
    ('track_out_program', 'Track-Out Programs'),
    ('half_day', 'Half-Day'),
    ('full_day', 'Full-Day'),
    ('academics', 'Academics'),
    ('animal_care', 'Animal Care'),
    ('arts_crafts', 'Arts & Crafts'),
    ('cooking_baking', 'Cooking & Baking'),
    ('games', 'Games'),
    ('health_fitness', 'Health & Fitness'),
    ('outdoor_play_nature', 'Outdoor & Nature'),
    ('performing_arts', 'Performing Arts'),
    ('sports', 'Sports'),
    ('technology', 'Technology'),
    ('other', 'Other'),
)

AGE_RANGE = (
    ('all_ages', 'All Ages'),
    ('preschool', 'Pre-K'),
    ('k_5', 'Elementary'),
    ('middle_school', 'Middle School'),
    ('high_school', 'High School'),
)

CLASS_CAMP = (
    ('class', 'Class'),
    ('camp', 'Camp'),
    ('homeschool', 'Homeschool'),
)

CITIES = (
    ('raleigh', 'Raleigh'),
    ('durham', 'Durham'),
    ('cary', 'Cary'),
    ('chapel_hill', 'Chapel Hill'),
    ('morrisville', 'Morrisville'),
    ('rtp', 'RTP'),
    ('carrboro', 'Carrboro'),
)


class Event(models.Model):
    type_choice = MultiSelectField(choices=EVENT_TYPE, null=True, blank=False)
    age_choice = models.CharField(
        max_length=20, null=True, blank=False, choices=AGE_RANGE)
    class_camp_choice = models.CharField(
        max_length=10, null=True, blank=False, choices=CLASS_CAMP)
    cities_choice = models.CharField(
        max_length=30, null=True, blank=False, choices=CITIES)
    date_created = models.DateTimeField(auto_now_add=True)
    business = models.ForeignKey(
        Business, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=255)
    link = models.URLField(null=True, blank=True)
    description = models.TextField()
    slug = models.SlugField(unique=True, max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    start_time = models.CharField(max_length=255)
    end_time = models.CharField(max_length=255)
    favorite = models.ManyToManyField(
        User, related_name='favorite', blank=True)
    image = models.ImageField(upload_to='test_image', blank=True)

    class Meta:
        verbose_name_plural = "Events"

    def __str__(self):
        return self.title


class EventLatLong(models.Model):
    event = models.OneToOneField(
        Event, on_delete=models.CASCADE, related_name='location', null=True)
    site_name = models.CharField(max_length=512, blank=True)
    relevance = models.FloatField(default=0)
    latitude = models.FloatField(blank=True)
    longitude = models.FloatField(blank=True)


class LeaveReview(models.Model):
    business_review = models.ForeignKey(
        Business, on_delete=models.CASCADE, related_name="reviews")
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=500, blank=False)
    title = models.CharField(max_length=75, blank=True)
    event = models.CharField(max_length=75, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1),
                    MaxValueValidator(5)])

    class Meta:
        verbose_name_plural = "Reviews"

    def __str__(self):
        return self.title


#class Location
# event location
#
# business location
# search box would be a map filter
# JS would take fields from search box to construct the map
# have a city that is "anywhere" that is show all
# how to get info in/out from database from JS...will need to do query against the db
# events in the next month
# js class map_builder
# create rest api that allows to get event data / manipulating objects in db
# only object that has access to python models is rest api
# "separation of concerns"
#
#
#
#
##
#
#
#

core/forms.py
from django.forms import ModelForm
from core.models import LeaveReview, Event
# from uni_form.helper import FormHelper
from crispy_forms.helper import FormHelper
from django import forms


class LeaveReviewForm(ModelForm):
    class Meta:
        model = LeaveReview
        fields = [
            'title', 'event', 'rating', 'text',
        ]
        help_texts = {
            'text': 'Please note: All reviews are monitored. We encourage you to be honest, but please be considerate when reviewing businesses and remain from using any inappropriate language. Thanks!',
        }
        labels = {
            'title': "Title of Review : ( Example: \"The yoga is fun!\" ) ",
         'event': "Is there an Activity or Event you are reviewing?  ( Example: \" Yoga at the Goat Farm ...\" )", 
         'rating': "Rating: ( Please provide a rating between 1-5 ) ", 
         'text': "My Review: ( Let us know what you think! ) ",
         
         }


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'title', 'link', 'description', 'start_date', 'end_date', 'start_time', 'end_time', 'image', 'type_choice', 'age_choice', 'class_camp_choice', 'address', 'city', 'state',
        ]


class NewEventForm (forms.Form):
    name = forms.CharField(label='Your name', max_length=150)
    email = forms.EmailField()
    event_name = forms.CharField(label='Name of Event', max_length=200)
    business = forms.CharField(label='Event Business', max_length=100)
    description = forms.CharField(label='Event Description', max_length=600)
    event_location = forms.CharField(label='Location of Event', max_length=100)
    event_date = forms.CharField(label='Date of Event')
    start_time = forms.CharField(label='Event start time')
    end_time = forms.CharField(label='Event end time')
    additional_info = forms.CharField(label=' Is this event online anywhere? ( if yes, please provide a link ) ')


class GeneralSubmitForm (forms.Form):
    name = forms.CharField(label='Your name', max_length=150)
    email = forms.EmailField()
    event_name = forms.CharField(label=' Message: ( Please note: If you are interested in submitting an event to us, please fill out our event submit form instead. Thanks! )', max_length=400)
    

core/templates/bsevent_directory.html
{% extends 'base.html' %}
{% block title %}
Event Directory - {{ block.super }}
{% endblock title %}
{% load bootstrap %}
{% load urls %}
{% block content %}

<!-- SECONDARY NAV AREA -->



<!-- Title Bar -->
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">


				<div class="search-result ">
				<br>

				
            <h2 class=" raleway ">Event Directory</h2>
			
            


					{% comment %} <h2 class="raleway">Event Directory</h2> {% endcomment %}
					<p> Browse Events in the Triangle </p>
					
					


				</div>

			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<div class="category-sidebar">
					


						

						<div class="widget category-list">
								<h4 class="widget-header">City</h4>
								<ul class="category-list">
							{% for cities_choice in cities_choices %}
							<li>
								{% if filter.data.cities_choice == cities_choice.0 %}
								<h2> {{ cities_choice.1 }} </h2> 
								{% else %}
								<a href="{% replace_query_param url=request.get_full_path param='cities_choice' value=cities_choice.0 %}">
									{{ cities_choice.1 }}
									</a>
								{% endif %}
							</li>
							{% endfor %}</li>
						</ul>
						</div>

					
						<div class="widget category-list">
							<h4 class="widget-header">Ages</h4>
							<ul class="category-list">

								{% for age_choice in age_choices %}
								<li>
									{% if filter.data.age_choice == age_choice.0 %}
									<h2>{{ age_choice.1 }} </h2> 
									{% else %}
									<a href="{% replace_query_param url=request.get_full_path param='age_choice' value=age_choice.0 %}">
										{{ age_choice.1 }}
										</a>
									{% endif %}
								</li>
								{% endfor %}</li>

							</ul>
						</div>

						<div class="widget category-list">
							<h4 class="widget-header">Type</h4>
							<ul class="category-list">
								{% for class_camp_choice in class_camp_choices %}
								<li>
									{% if filter.data.class_camp_choice == class_camp_choice.0 %}
									 <h2> {{ class_camp_choice.1 }} </h2> 
									{% else %}
									<a href="{% replace_query_param url=request.get_full_path param='class_camp_choice' value=class_camp_choice.0 %}">
										{{ class_camp_choice.1 }}
										</a>
									{% endif %}
								</li>
								{% endfor %}</li>

							</ul>

						</div>


						

						

						<div class="container">




							{% comment %}
							<ul>
								{% for event in filter.qs %}
								<li>

									{{ event.title }} - {{ event.class_camp_choice }}
									<p>{{ event.start_date }} - {{ event.end_date }}</p>
									<p>{{ event.start_time }} - {{ event.end_time }}</p>
									<p>{{ event.type_choice }}</p>
									<p>{{ event.get_age_choice_display }}</p>
									<p>{{ event.get_cities_choice_display }}</p>
									<p>{{ event.business }}</p>
									<p>{{ event.link }}</p>
									<p>{{ event.description }}</p>
									<p>{{ event.address }}</p>
									<!-- <p>{{ event.city }}</p> -->
									<!-- <p>{{ event.favorite }}</p> -->

								</li>
								{% endfor %}
							</ul> {% endcomment %}

						</div>

					</div>
				</div>
				<div class="col-md-9">
					
					
							
						
						
						<a class="text-large "href="{% url 'event_list_preset' %}"><i class="fa fa-th-large"></i> See All Events</a>
						

						 <div class="inline" id="accordion">
					
							<p  class="inline goright" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" >
									<a href="#">  Filter Events By Category
									<span ></a>
									<i class="fa fa-angle-down fa-1x" style="color:#D01C2E;"></i>  </span>
									</p>
									<div >
								{% for type_choice in type_choices %}
								<div id="collapseOne" class="collapse list-inline-item " style="text-align: center" aria-labelledby="headingOne" data-parent="#accordion">

										{% if filter.data.type_choice__icontains == type_choice.0 %}
										
										<button class="btn-round-xs success">{{ type_choice.1 }}</button>
									
										{% else %}
										
										<button button type="button" class="btn-round-xs" > <a href="{% replace_query_param url=request.get_full_path param='type_choice__icontains' value=type_choice.0 %}">
											{{ type_choice.1 }}</button>
										</a>
											
										{% endif %}
									
									
							</div>
								{% endfor %}
								</div>
								
								
							
						
					</div>
					 
					







						{% comment %} BUTTON STUFF {% for type_choice in type_choices %}
								
									{% if filter.data.type_choice__icontains == type_choice.0 %}
									<button class="widget-header">{{ type_choice.1 }}</button>
									{% else %}
									<button button type="button" class=" btn-round-xs btn btn-outline-secondary" > <a href="{% replace_query_param url=request.get_full_path param='type_choice__icontains' value=type_choice.0 %}">
										{{ type_choice.1 }}</button>
										
									{% endif %}
								
								{% endfor %} {% endcomment %}
						
						


						<div class="row mt-30">
						
							<!-- THIS FOR LOOP HANDLES THE SEARCH QUERY  -->

							{% for event in filter.qs %}
							<div class="col-sm-12 col-lg-4 col-md-6">
								<div class="product-item bg-light">




									<div class="card profile-card-2 roundit sppad">
										<div class="card-img-block">
													{% if event.image %}
													<img class=" roundit img-fluid " src="{{ event.image.url }}" alt="Card image cap" />
													
													{% else %}
													<img class="img-fluid roundit" src="https://images.pexels.com/photos/877695/pexels-photo-877695.jpeg?auto=compress&cs=tinysrgb&h=350" alt="Card image cap" />
													{% endif %} 
											
										</div>
										<div class="card-body pt-3 ">
										<ul class="list-inline product-meta">
										<h5 class="card-title list-inline-item"><a href="{% url 'event_detail' slug=event.slug %}">{{event.title}}</h5></a>
												<li class="list-inline-item">
													<p>{{event.business }}  <p>
												</li>
												
											
											
											<ul class="list-inline product-meta">
												<li class="list-inline-item">
													<i class="fa fa-calendar" style="color:#009999;" ></i> {{event.start_date }} 
												</li>
												<li class="list-inline-item">
													<i class="fa fa-user" style="color:#ffbb33;" ></i> {{event.get_age_choice_display}} 
												</li>
												<li class="list-inline-item">
													<i class="fa fa-location-arrow" style="color:#D01C2E;"></i> {{event.city}} 
												</li>
											</ul>
											
											<p> {{event.description|slice:":100"}}...</p>
											{% if event.type_choice %}
												<p class="list-inline-item"> <i style="color:#1C76D0;" class="fas fa-globe-americas"></i> {{event.type_choice }}</p>
											{% endif %}
								<br>
											{% comment %} <div class="icon-block centerit "><a href="#"><i style="color:#31B91C;" class="fas fa-chevron-circle-right"></i> See This Business </a></div> {% endcomment %}
											<a href="{% url 'event_detail' slug=event.slug %}"><button type="button" class="btn btn-outline-secondary btn-lg btn-block"> See This Event <i style="color:#31B91C;" class="fas fa-angle-double-right"></i> </button></a>
											</ul>
										</div>
									</div>







								</div>
							</div>
							{% endfor %}






							<!-- junk Event FOR Loop  -->


							<div class="advance-search">

								<div class="row">

									{% comment %} {% for event in event_list %}

									<div>
										<div>
											<h1><a href="{% url 'event_detail' slug=event.slug %}"> Name:{{event.title}} </a></h1>
											<h2>Address:{{event.address }} </h2>
											<!-- <p>EVENT RATING: {{event.average_rating}}</p> -->
											<p> ______________________________________________ <p>
										</div>
									</div>
									{% endfor %} {% endcomment %}




									<!-- THIS FOR LOOP IS NOT WORKING  -->

									{% for event in events %}
									<div class="col-sm-12 col-lg-4 col-md-6">


										<div class="product-item bg-light">

											<div class="card">
												{% if event.image %}
												<div class="thumb-content">
													<img class="mr-3" height="100" width="100" src="{{ event.image.url }}" alt="Generic placeholder image">
												</div>
												{% endif %}
												<div class="card-body">
													<h4><a href="{% url 'event_detail' slug=event.slug %}"> {{event.title}} </a></h4>
													<ul class="list-inline product-meta">
														<li class="list-inline-item">
															<p>{{ event.get_class_camp_choice_display }} </p>
														</li>
														<li class="list-inline-item">
															<p> {{event.description }} </p>
														</li>
														<li class="list-inline-item">
															<p> {{event.address }} </p>
														</li>
														<li class="list-inline-item">
															<p> {{ event.city }} </p>
														</li>

														<li class="list-inline-item">
															<p>{{ event.type_choice }} </p>
														</li>
														<li class="list-inline-item">
															<p>Age Range: {{ event.get_age_choice_display }} </p>
														</li>

													</ul>

													<div class="product-ratings">
														<ul class="list-inline">
															<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
															<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
															<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
															<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
															<li class="list-inline-item"><i class="fa fa-star"></i></li>
														</ul>
													</div>
												</div>
											</div>






											
										</div>
									</div>
									{% endfor %}

								</div>


							</div>





						</div>
						<!-- <div class="pagination justify-content-center">
					<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
									<span class="sr-only">Previous</span>
								</a>
							</li>
							<li class="page-item"><a class="page-link" href="#">1</a></li>
							<li class="page-item active"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Next">
									<span aria-hidden="true">&raquo;</span>
									<span class="sr-only">Next</span>
								</a>
							</li>
						</ul>
					</nav>
				</div> -->


					</div>
				</div>
			</div>
</section>
{% endblock content %}

core/templates/generalsubmit.html
{% extends 'base.html' %} 
{% load staticfiles %} 

{% block title %}
Submit an Event - {{ block.super }} 
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}


    <div class="container">




<h1 class="fonttitle "> Get in touch   </h1>
<p>  Feel free to contact us! </p>

                        {% if messages %}
							{% for message in messages %}
								<div id="notification" class="message-header">
								<h2>{{ message }} </h2> 
								</div>
							{% endfor %}
						{% endif %}



		<div class="row">

            <form role="form" action="" method="post" >
            {% csrf_token %}
            <table>{{form|crispy}}</table>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <br>
        

          {% endblock %}
   

core/templates/index.html
{% extends 'base.html' %} 
{% block title %}
Homepage - {{ block.super }} 
{% endblock title %}

{% block content %}



    <h1 class="subtitle">-------------Businesses-------------------</h1>
    {% for biz in businesses %}
    
        <div class="panel panel-default businesses">  
            <div class="panel  business">    
                <h1><a href="{% url 'bsbusiness_detail' slug=biz.slug %}"> Name:{{biz.name}} </a></h1>
                <hr>
            </div>
        </div>

    <h1 class="subtitle">-------------Events-------------------</h1>
    <br>
    <br>
    {% for event in events %}
    
        <div class="panel panel-default">  
            <div class="panel ">    
                <h1><a href="{% url 'event_detail' slug=event.slug %}"> Event Title:{{event.title}} </a></h1>
                <h2>Business:{{event.business }} </h2>
                <p>Description: {{event.description}}</p>
                <p>_________________________________</p>
        </div>
        </div>

    {% endfor %}

    
    


{% endblock content %}

core/templates/mapBoxPlotTest.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <style>
      body {
        margin: 0;
        padding: 0;
      }

      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
</head>
<body>
{% comment %} TO DO: add to business detail page {% endcomment %}
<label bizId="{pk}" class="bizinfo hidden" visible=false>

<div id='map' class="this that"></div>

<script>
  // TODO: RESTAPI:
  // http://localhost:8000/api/business/latlong/id/{pk}
  // return JSON: { "id"="74", "name"="BIZ 1" "address"="" "latitude": 34.32, "longitude": -84.2 }

  // http://localhost:8000/api/business/latlong/name/{name}
  // return JSON: { "id"="74", "name"="BIZ 1" "address"="" "latitude": 34.32, "longitude": -84.2 }

  // http://localhost:8000/api/business/latlong/name/all
  // return JSON: { [ "entries": [
  //        { "id"="74", "name"="BIZ 1" "address"="" "latitude": 34.32, "longitude": -83.22 },
  //        { "id"="12", "name"="BIZ 2" "address"="" "latitude": 34.33, "longitude": -84.25 },

mapboxgl.accessToken = 'pk.eyJ1IjoidHJpYW5nbGU0a2lkcyIsImEiOiJjanFubWRwMGw3a2hjNGFtc3RrMWQ4OXl5In0.eZj0i5qyOBlmeY2oH6LWow';

var map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/light-v9',
  center: [-96, 37.8],
  zoom: 3
});
{% comment %} 
// code from the next step will go here!
var geojson = {
  type: 'FeatureCollection',
  features: [{
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [-77.032, 38.913]
    },
    properties: {
      title: 'Mapbox',
      description: 'Washington, D.C.'
    }
  },
  {
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [-122.414, 37.776]
    },
    properties: {
      title: 'Mapbox',
      description: 'San Francisco, California'
    }
  }]
}; {% endcomment %}

{% comment %} geojson.features.forEach(function(entry) {
  addLatLongMarker(entry.geometry.coordinates[1],entry.geometry.coordinates[0])
  }); {% endcomment %}


addLatLongMarker(35.90, -79.01)
{% comment %} use jquery to get the biz pk we need
 {% endcomment %}


{% comment %} // add markers to map
geojson.features.forEach(function(marker) {

  // create a HTML element for each feature
  var el = document.createElement('div');
  el.className = 'marker';



  // make a marker for each feature and add to the map
  new mapboxgl.Marker(el)
    .setLngLat(marker.geometry.coordinates)
    .addTo(map);
}); {% endcomment %}

function addLatLongMarker(latitude, longitude) {
  // create a HTML element for each feature
  var el = document.createElement('div');
  el.className = 'marker';

  // TODO: RESTAPI:
  // http://localhost:8000/api/business/{pk}/latlong
  // return JSON: { "latitude": 34.32, "longitude": -84.2.232 }

  coords= [longitude, latitude]
  // make a marker for each feature and add to the map
  new mapboxgl.Marker(el)
    .setLngLat(coords)
    .addTo(map);
}
</script>

</body>
</html>